-- Migration: Expand betonara_production table with flattened material measurement columns
-- Created: 2026-02-08

ALTER TABLE public.betonara_production 
ADD COLUMN IF NOT EXISTS company TEXT,
ADD COLUMN IF NOT EXISTS customer TEXT,
ADD COLUMN IF NOT EXISTS end_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS production_no TEXT,
ADD COLUMN IF NOT EXISTS recipe_no TEXT,
ADD COLUMN IF NOT EXISTS receipt TEXT,
ADD COLUMN IF NOT EXISTS target_quantity NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS return_concrete NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS return_concrete_note TEXT,
ADD COLUMN IF NOT EXISTS order_code TEXT,
ADD COLUMN IF NOT EXISTS jobsite TEXT,
ADD COLUMN IF NOT EXISTS driver TEXT,
ADD COLUMN IF NOT EXISTS vehicle TEXT,
ADD COLUMN IF NOT EXISTS shipping_zone TEXT,
ADD COLUMN IF NOT EXISTS extra_material_1 TEXT,
ADD COLUMN IF NOT EXISTS extra_material_1_qty NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS extra_material_2 TEXT,
ADD COLUMN IF NOT EXISTS extra_material_2_qty NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS status TEXT,
ADD COLUMN IF NOT EXISTS extra_water_1 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS extra_water_2 NUMERIC DEFAULT 0;

-- Aggregates 1-6
ALTER TABLE public.betonara_production 
ADD COLUMN IF NOT EXISTS agg1_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg1_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg1_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg1_pct NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg1_moisture NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS agg2_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg2_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg2_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg2_pct NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg2_moisture NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS agg3_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg3_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg3_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg3_pct NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg3_moisture NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS agg4_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg4_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg4_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg4_pct NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg4_moisture NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS agg5_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg5_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg5_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg5_pct NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg5_moisture NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS agg6_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg6_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg6_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg6_pct NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS agg6_moisture NUMERIC DEFAULT 0;

-- Cements 1-4
ALTER TABLE public.betonara_production 
ADD COLUMN IF NOT EXISTS cem1_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem1_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem1_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem1_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cem2_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem2_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem2_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem2_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cem3_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem3_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem3_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem3_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cem4_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem4_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem4_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS cem4_pct NUMERIC DEFAULT 0;

-- Additives 1-5
ALTER TABLE public.betonara_production 
ADD COLUMN IF NOT EXISTS add1_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add1_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add1_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add1_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS add2_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add2_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add2_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add2_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS add3_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add3_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add3_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add3_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS add4_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add4_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add4_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add4_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS add5_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add5_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add5_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS add5_pct NUMERIC DEFAULT 0;

-- Water 1-2
ALTER TABLE public.betonara_production 
ADD COLUMN IF NOT EXISTS water1_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS water1_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS water1_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS water1_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS water2_actual NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS water2_target NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS water2_error NUMERIC DEFAULT 0, ADD COLUMN IF NOT EXISTS water2_pct NUMERIC DEFAULT 0;

-- Drop obsolete JSON column if you want strict flattening (optional, keeping for now to avoid data loss on existing records)
-- ALTER TABLE public.betonara_production DROP COLUMN IF EXISTS technical_data;
